// src/index.js
// Entry point for the React PWA application.
// This file will import the root component (App) and render it.
// Build tools (Vite) will use this as the main entry.
import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.jsx';
import './index.css'; // Tailwind CSS entry (will be generated by Vite)

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
